import { defineGraphSeedPack } from '../src/index.js';

export const algebraSeedPack = defineGraphSeedPack({
  schemaVersion: 1,
  id: 'intro-algebra-v1',
  title: 'Introductory algebra',
  description: 'A deliberately small example showing that the primitives are independent of language learning.',
  author: {
    kind: 'human',
    model: 'none',
    promptVersion: 'manual-v1',
    generatedAt: '2026-07-21T00:00:00.000Z',
  },
  sources: [
    {
      id: 'open-algebra-standard',
      title: 'Example open algebra standard',
      url: 'https://example.com/algebra-standard',
      license: 'CC BY 4.0',
      notes: 'Illustrative source metadata for the example pack.',
    },
  ],
  sourceIds: ['open-algebra-standard'],
  provenancePolicy: {
    policyVersion: 'example-v1',
    externalSourceRequiredFor: ['canonical_concepts'],
    modelGeneratedAllowedFor: ['task_variants'],
    promoteModelGeneratedWhen: ['validation_passes'],
    quarantineWhen: ['source_missing'],
  },
  provenanceClaims: [
    {
      targetType: 'seed_pack',
      targetId: 'intro-algebra-v1',
      provenanceKind: 'external_source',
      riskLevel: 'low',
      requiresExternalSource: true,
      sourceIds: ['open-algebra-standard'],
      modelConfidence: 1,
      validationMethods: ['human_review'],
      rationale: 'The example follows the linked standard.',
    },
    ...['recognize-variable', 'solve-one-step-addition'].map((targetId) => ({
      targetType: 'node' as const,
      targetId,
      provenanceKind: 'external_source' as const,
      riskLevel: 'low' as const,
      requiresExternalSource: true,
      sourceIds: ['open-algebra-standard'],
      modelConfidence: 1,
      validationMethods: ['human_review'],
      rationale: 'The atomic skill is anchored to the example standard.',
    })),
    ...['task-recognize-variable', 'task-solve-one-step-addition'].map((targetId) => ({
      targetType: 'task' as const,
      targetId,
      provenanceKind: 'model_generated' as const,
      riskLevel: 'low' as const,
      requiresExternalSource: false,
      sourceIds: [] as string[],
      modelConfidence: 0.9,
      validationMethods: ['unit_test'],
      rationale: 'The task is a generated practice variant over a sourced concept.',
    })),
  ],
  courses: [
    {
      id: 'course-intro-algebra',
      title: 'Introductory algebra',
      description: 'A two-node course route.',
      targetLevelId: 'foundation',
      goal: { outcome: 'Solve a one-step addition equation.' },
    },
  ],
  courseNodes: [
    { courseId: 'course-intro-algebra', nodeId: 'recognize-variable', sequence: 1, required: true, weight: 1 },
    { courseId: 'course-intro-algebra', nodeId: 'solve-one-step-addition', sequence: 2, required: true, weight: 1 },
  ],
  nodes: [
    {
      id: 'recognize-variable',
      kind: 'concept',
      levelId: 'foundation',
      granularity: 'micro_skill',
      parentNodeId: null,
      domainId: 'algebraic-notation',
      atomic: true,
      title: { primary: 'Recognize a variable', secondary: null },
      description: 'Identify the symbol that stands for an unknown quantity.',
      canonicalScope: 'Select the variable in a one-variable arithmetic expression.',
      nonGoals: ['Does not require solving an equation.'],
      skillIds: ['recognition'],
    },
    {
      id: 'solve-one-step-addition',
      kind: 'procedure',
      levelId: 'foundation',
      granularity: 'micro_skill',
      parentNodeId: null,
      domainId: 'linear-equations',
      atomic: true,
      title: { primary: 'Solve a one-step addition equation', secondary: null },
      description: 'Undo addition to isolate one variable.',
      canonicalScope: 'Solve equations of the form x + a = b using inverse operations.',
      nonGoals: ['Does not include multiplication or negative coefficients.'],
      skillIds: ['procedural-fluency'],
    },
  ],
  edges: [
    {
      fromNodeId: 'recognize-variable',
      toNodeId: 'solve-one-step-addition',
      relation: 'prerequisite',
      weight: 0.9,
      reason: 'The learner must identify the unknown before isolating it.',
      confidence: 0.95,
    },
  ],
  interferenceSets: [],
  interferenceSetNodes: [],
  knowledgePoints: [
    {
      id: 'kp-recognize-variable',
      nodeId: 'recognize-variable',
      sequence: 1,
      title: 'Locate the unknown symbol',
      description: 'Point to the symbol whose value is not supplied.',
      keyPrerequisiteNodeIds: [],
      targetSkillIds: ['recognition'],
    },
    {
      id: 'kp-inverse-addition',
      nodeId: 'solve-one-step-addition',
      sequence: 1,
      title: 'Apply the inverse operation',
      description: 'Subtract the same amount from both sides.',
      keyPrerequisiteNodeIds: ['recognize-variable'],
      targetSkillIds: ['procedural-fluency'],
    },
  ],
  knowledgePointPrerequisites: [
    {
      knowledgePointId: 'kp-inverse-addition',
      prerequisiteNodeId: 'recognize-variable',
      prerequisiteKnowledgePointId: 'kp-recognize-variable',
      skillId: 'recognition',
      weight: 0.8,
      distance: 1,
      rationale: 'The learner must track which term is the unknown.',
    },
  ],
  objectives: [
    {
      id: 'objective-recognize-variable',
      nodeId: 'recognize-variable',
      skillId: 'recognition',
      levelId: 'foundation',
      prompt: 'Identify the variable in 7 + n.',
      successCriteria: 'The learner selects n without a hint.',
    },
    {
      id: 'objective-solve-one-step-addition',
      nodeId: 'solve-one-step-addition',
      skillId: 'procedural-fluency',
      levelId: 'foundation',
      prompt: 'Solve x + 3 = 8.',
      successCriteria: 'The learner gives x = 5 and applies the inverse operation correctly.',
    },
  ],
  taskVariants: [
    createTask('task-recognize-variable', 'recognize-variable', 'recognition'),
    createTask('task-solve-one-step-addition', 'solve-one-step-addition', 'procedural-fluency'),
  ],
  failureMappings: [
    {
      id: 'failure-solve-to-recognize',
      failedNodeId: 'solve-one-step-addition',
      suspectedPrerequisiteNodeId: 'recognize-variable',
      skillId: 'procedural-fluency',
      confidence: 0.6,
      rationale: 'Manipulating the wrong term can indicate weak variable recognition.',
    },
  ],
  diagnosticCoverage: [
    {
      id: 'diagnostic-recognize-variable',
      taskVariantId: 'task-recognize-variable',
      nodeId: 'recognize-variable',
      skillId: 'recognition',
      successImpliesMastery: 0.8,
      failureImpliesGap: 0.9,
      informationGain: 0.75,
      notes: 'A cheap early frontier probe.',
    },
  ],
  implicitReviewRules: [
    {
      id: 'review-variable-through-equation',
      fromNodeId: 'solve-one-step-addition',
      toNodeId: 'recognize-variable',
      skillId: 'recognition',
      modalityId: 'written',
      fractionalCredit: 0.25,
      minEvidenceScore: 0.75,
      minConfidence: 0.6,
      reason: 'Solving the equation exercises variable recognition.',
    },
  ],
  qualityTargets: {
    minimumNodes: 2,
    minimumEdgesPerNode: 0.5,
    minimumKnowledgePointsPerAtomicNode: 1,
    minimumTaskVariantsPerAtomicNode: 1,
    minimumDiagnosticCoverage: 0.5,
  },
});

function createTask(id: string, nodeId: string, skillId: string) {
  return {
    id,
    nodeId,
    kind: 'practice' as const,
    stage: 'retrieval' as const,
    scaffoldingLevel: 'unaided' as const,
    activityFormat: 'short_answer',
    levelId: 'foundation',
    difficulty: 0.35,
    cognitiveLoad: 0.3,
    estimatedMinutes: 2,
    expectedResponseTimeMs: 20_000,
    effortValue: 2,
    targetScoreThreshold: 0.8,
    retryPolicy: { maxAttempts: 2, fallback: 'worked_example' },
    haltThreshold: 2,
    allowedScaffolds: ['cued'],
    modalityWeights: { written: 1 },
    quizzable: true,
    examLike: false,
    taskFamilyId: `family-${nodeId}`,
    nearDuplicateTaskIds: [],
    inputSkillIds: [skillId],
    outputSkillIds: [skillId],
    interactionContract: { response: 'short_answer' },
    offlineCalibration: { expectedPassRate: 0.7, needsLiveCalibration: true },
    promptTemplate: { prompt: `Demonstrate ${nodeId}.` },
    successCriteria: `The learner demonstrates ${nodeId} without a hint.`,
  };
}
